name: build-and-test
on:
  workflow_dispatch:
  pull_request:
jobs:
  build-and-test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install autotools dependencies
        run: sudo apt-get update && sudo apt-get install -y automake autoconf libtool
      - name: autoreconf, configure, build and test via autogen.sh
        working-directory: cola
        run: ./autogen.sh

  build-and-test-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: install conan
        run: pip install conan

      - name: create conan profile
        run: conan profile detect --force

      - name: conan install dependencies
        run: conan install . --output-folder=build --build=missing

      - name: build using cmake
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
          cmake --build . --config Release
